### PR TITLE
Update 2020-06-03-rogers20a.md

### PR DESCRIPTION
**Pull request by omthkkr**
Correcting personal name.

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
The correction only seems to be to the bibtex authors field, they need to be to the authors field also.

**Comment by omthkkr** [comment]
Sorry I'm not sure if I should be making the change (and if so, where might that be)? Thank you.

**Comment by lawrennd** [comment]
In that file, author names appear twice. Once is for bibtex formating (which you changed), the other is the main source of author info under the subtitle 'author'.


Neil
--
Professor Neil Lawrence
http://inverseprobability.com
________________________________

**Comment by omthkkr** [comment]
Ah, I saw the complete file and saw the place where the 2nd change needed to be made. Thanks for the detailed explanation!

**Review by lawrennd — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
